pipeline
{

agent {
  label 'dev-server'
}
stages{

    stage('build')
    {
        steps{
            sh 'mvn clean package'
'
            }


        post {
        success {
            archiveArtifacts 'target/*.war'
                }
            }

    }

    
    }
    
}    

