pipeline
{

agent {
  label 'dev-server'
}
stages{

    stage('build')
    {
        steps{
            sh 'mvn -B -DskipTests clean package"
            }


        post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
                }
            }

    }

    
    }
    
}    

